name: ZbingoReload
version: '${project.version}'
main: cl.vadnir.zbingoreload.ZBingoReload
api-version: 1.19
depend: [UltimateAdvancementAPI, CommandAPI, PlaceholderAPI]
softdepend: [UltimateAdvancementAPI]